// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/guitarlnw/golang-practices/model"
	mock "github.com/stretchr/testify/mock"
)

// IUserModel is an autogenerated mock type for the IUserModel type
type IUserModel struct {
	mock.Mock
}

// GetUserByID provides a mock function with given fields: id, result
func (_m *IUserModel) GetUserByID(id string, result *model.UserModel) error {
	ret := _m.Called(id, result)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *model.UserModel) error); ok {
		r0 = rf(id, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
