// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
)

// IUserCtl is an autogenerated mock type for the IUserCtl type
type IUserCtl struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: c
func (_m *IUserCtl) GetUser(c *fiber.Ctx) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
